### ISSUE TITLE
BLE Vs Bluetooth Classic

### ISSUE THREAD

**Issue by nevsie** [hxelec/antc3#1]
I love everything you have done here, congrats.
I am doing similar with a esp32 D1 mini board, but external esc and bec. The reason I chose this board is to use cheap gaming controllers, but they require Bluetooth classic. 

Yes, it means a bigger heavier board than BLE..
But I wondered if you'd consider a variant of your board with this on board?

I then use the Bluepad32 library as the basis for connecting the controller. This allows everything from Xbox, pc, PS3, PS4, PS4, android, iOS, switch, Wii, etc. I'd love to drive with the Wii wheel!

I hope you'd consider.
Thanks, N

**Comment by hxelec** [comment]
Hi nevsie, I would be happy to consider a variant of this board with a classic ESP32 chip, using the ESP32-PICO-MINI-02 module, but unfortunately, I would have no use for it over just the ESP32-C3 I'm using, since ESP-NOW communication (which works with every ESP chip) is being used for my application. If you'd like me to design you a board with the ESP32 chip instead of the ESP32-C3, in exchange for payment, and then send you all the manufacturing files once I'm done, I would be happy to do that, and you can contact me: brixdownunder@gmail.com.

**Comment by nevsie** [comment]
Hi and thanks for your reply. 
Completely understand your direction, and decisions. 

My mentality is that using existing gaming controllers is a great, familiar, way to control the bots. They are very cheap even if you do not have old ones in the draw somewhere to recycle. 

I have since been pushed towards the ESP Pico-d4 chip, as this does both BLE and classic, and a tiny ceramic antenna. 

Thanks for the offer of design. But like you and many others, I am intending to open source it so will be trying to keep costs down. 

Good luck with yours, I'd love to see you controller expand. N

**Comment by nevsie** [comment]
Closing this now.
